//! Cross-language predicate + sort-spec golden fixture test.
//!
//! The file `fixtures/golden_predicate_sort.json` is generated by the *Dart*
//! encoder (`dart run tool/gen_golden_fixtures.dart`). It carries:
//!   * Dart-encoded predicate payloads and sort-spec payloads (hex);
//!   * a shared codec-encoded row set (hex);
//!   * the expected match set per predicate and expected row order per sort
//!     spec, computed by Dart's `Filter.matchesValue` and `compareRows`.
//!
//! This test decodes the payloads with the *Rust* decoders and must reproduce
//! the Dart-computed expectations exactly — proving the two implementations
//! agree on the same logical contract, not just on a self-consistent format.

use gecko_db_rust::predicate::decode_predicate;
use gecko_db_rust::sort_spec::{ compare_rows, decode_sort_specs };
use gecko_db_rust::value_codec::{ self, RowValue };
use serde_json::Value;
use std::collections::BTreeMap;
use std::path::PathBuf;

fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("golden_predicate_sort.json")
}

/// Decodes a lowercase hex string (no separators) to bytes.
fn hex_decode(hex: &str) -> Vec<u8> {
    let clean: String = hex
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    assert_eq!(clean.len() % 2, 0, "hex length must be even: {hex}");
    let mut out = Vec::with_capacity(clean.len() / 2);
    let bytes = clean.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let hi = (bytes[i] as char).to_digit(16).expect("hex hi nibble");
        let lo = (bytes[i + 1] as char).to_digit(16).expect("hex lo nibble");
        out.push(((hi << 4) | lo) as u8);
        i += 2;
    }
    out
}

fn as_str<'a>(v: &'a Value, what: &str) -> &'a str {
    v.as_str().unwrap_or_else(|| panic!("{what} must be a string"))
}

/// Decodes the fixture's shared row set into `key -> encoded value bytes`.
/// The encoded bytes are what `Predicate::test_bytes` evaluates; the decoded
/// `RowValue` (via [decode]) is what `compare_rows` orders.
fn rows(v: &Value) -> BTreeMap<String, Vec<u8>> {
    let mut map = BTreeMap::new();
    for row in v["rows"].as_array().expect("rows array") {
        let key = as_str(&row["key"], "row key").to_string();
        map.insert(key, hex_decode(as_str(&row["hex"], "row hex")));
    }
    map
}

fn decode(bytes: &[u8]) -> RowValue {
    value_codec::decode_value(bytes).expect("row must decode in Rust")
}

#[test]
fn dart_predicates_evaluate_to_the_expected_match_sets() {
    let fixture: Value = serde_json
        ::from_str(&std::fs::read_to_string(fixture()).expect("fixture must exist"))
        .expect("fixture JSON must parse");
    let rows = rows(&fixture);

    for entry in fixture["predicates"].as_array().expect("predicates array") {
        let label = as_str(&entry["label"], "predicate label");
        let bytes = hex_decode(as_str(&entry["hex"], "predicate hex"));
        let predicate = decode_predicate(&bytes).unwrap_or_else(|e|
            panic!("predicate {label} must decode in Rust: {e}")
        );

        // Evaluate against every row in fixture order.
        let mut matched: Vec<&str> = Vec::new();
        for (key, encoded) in &rows {
            if predicate.test_bytes(encoded) {
                matched.push(key.as_str());
            }
        }

        let expected: Vec<&str> = fixture["expectedMatches"][label]
            .as_array()
            .unwrap_or_else(|| panic!("expectedMatches[{label}] must exist"))
            .iter()
            .map(|k| k.as_str().expect("match key"))
            .collect();
        assert_eq!(matched, expected, "predicate {label} match set");
    }
}

#[test]
fn dart_predicates_match_the_same_rows_the_worker_contract_expects() {
    let fixture: Value = serde_json
        ::from_str(&std::fs::read_to_string(fixture()).expect("fixture must exist"))
        .expect("fixture JSON must parse");
    let rows = rows(&fixture);

    // An empty predicate must match everything (Dart FilterGroup contract).
    let empty = decode_predicate(
        &hex_decode(as_str(&fixture["predicates"][4]["hex"], "empty predicate hex"))
    ).expect("empty predicate decodes");
    assert!(empty.is_empty());
    for encoded in rows.values() {
        assert!(empty.test_bytes(encoded));
    }

    // A prefix predicate must not match non-strings or missing fields.
    let prefix = decode_predicate(
        &hex_decode(as_str(&fixture["predicates"][3]["hex"], "prefix predicate hex"))
    ).expect("prefix predicate decodes");
    assert!(prefix.test_bytes(&rows["r0"]));
    assert!(!prefix.test_bytes(&rows["r4"]));
}

#[test]
fn dart_sort_specs_order_rows_to_the_expected_order() {
    let fixture: Value = serde_json
        ::from_str(&std::fs::read_to_string(fixture()).expect("fixture must exist"))
        .expect("fixture JSON must parse");
    let rows = rows(&fixture);

    for entry in fixture["sortSpecs"].as_array().expect("sortSpecs array") {
        let label = as_str(&entry["label"], "sort spec label");
        let bytes = hex_decode(as_str(&entry["hex"], "sort spec hex"));
        let specs = decode_sort_specs(&bytes).unwrap_or_else(|e|
            panic!("sort spec {label} must decode in Rust: {e}")
        );

        // Order the rows with Rust compare_rows, tie-broken by key (matching
        // the Dart generator and the query engine).
        let mut keys: Vec<&String> = rows.keys().collect();
        keys.sort_by(|a, b| {
            let ord = compare_rows(&decode(&rows[*a]), &decode(&rows[*b]), &specs.specs);
            if ord != std::cmp::Ordering::Equal {
                ord
            } else {
                a.cmp(b)
            }
        });

        let expected: Vec<&str> = fixture["expectedOrder"][label]
            .as_array()
            .unwrap_or_else(|| panic!("expectedOrder[{label}] must exist"))
            .iter()
            .map(|k| k.as_str().expect("order key"))
            .collect();
        let actual: Vec<&str> = keys
            .into_iter()
            .map(|k| k.as_str())
            .collect();
        assert_eq!(actual, expected, "sort spec {label} order");
    }
}

#[test]
fn dart_sort_specs_reproduce_the_ascending_and_descending_contract() {
    let fixture: Value = serde_json
        ::from_str(&std::fs::read_to_string(fixture()).expect("fixture must exist"))
        .expect("fixture JSON must parse");
    let rows = rows(&fixture);

    // age-asc first element is the smallest age (r9 = age 0).
    let asc = decode_sort_specs(
        &hex_decode(as_str(&fixture["sortSpecs"][0]["hex"], "age-asc hex"))
    ).expect("age-asc decodes");
    assert_eq!(asc.specs.len(), 1);
    assert!(!asc.specs[0].descending);
    let mut ascending: Vec<&String> = rows.keys().collect();
    ascending.sort_by(|a, b| compare_rows(&decode(&rows[*a]), &decode(&rows[*b]), &asc.specs));
    assert_eq!(ascending[0], "r9", "age-asc must place the smallest age first");

    // age-desc is the exact reverse of age-asc (no ties in the fixture).
    let desc = decode_sort_specs(
        &hex_decode(as_str(&fixture["sortSpecs"][1]["hex"], "age-desc hex"))
    ).expect("age-desc decodes");
    assert!(desc.specs[0].descending);
    let mut descending: Vec<&String> = rows.keys().collect();
    descending.sort_by(|a, b| compare_rows(&decode(&rows[*a]), &decode(&rows[*b]), &desc.specs));
    ascending.reverse();
    assert_eq!(descending, ascending, "descending order must invert ascending");
}

/// Rebuilds a `RowValue` from the fixture's JSON-tagged representation
/// (`{"type": ..., "value": ...}`, maps as ordered pairs).
fn tagged_to_row(v: &Value) -> RowValue {
    use RowValue::*;
    match v["type"].as_str().expect("tag type") {
        "null" => Null,
        "bool" => Bool(v["value"].as_bool().expect("bool value")),
        "int" => Int64(v["value"].as_i64().expect("int value")),
        "datetime" => DateTime(v["value"].as_i64().expect("datetime value")),
        "bigint" => {
            let s = v["value"].as_str().expect("bigint value");
            BigInt(s.parse().expect("bigint parses"))
        }
        "f64" => match v["value"].as_str() {
            Some("inf") => F64(f64::INFINITY),
            Some("-inf") => F64(f64::NEG_INFINITY),
            Some("nan") => F64(f64::NAN),
            _ => F64(v["value"].as_f64().expect("f64 value")),
        },
        "string" => String(v["value"].as_str().expect("string value").to_string()),
        "bytes" => Bytes(hex_decode(v["value"].as_str().expect("bytes hex"))),
        "list" => List(
            v["value"]
                .as_array()
                .expect("list array")
                .iter()
                .map(tagged_to_row)
                .collect(),
        ),
        "map" => Map(
            v["value"]
                .as_array()
                .expect("map array")
                .iter()
                .map(|pair| {
                    let arr = pair.as_array().expect("map pair");
                    (tagged_to_row(&arr[0]), tagged_to_row(&arr[1]))
                })
                .collect(),
        ),
        other => panic!("unknown tag type {other}"),
    }
}

/// The durable-index composite key
/// `[0x06, u32(4)] | encode(table) | encode(field) |
/// ordered_index_element(value) | encode(recordId)`, mirroring the Dart
/// `_indexKey` in `tool/gen_golden_fixtures.dart`.
fn index_key_bytes(table: &str, field: &str, value: &RowValue, record_id: &str) -> Vec<u8> {
    let mut out = vec![value_codec::TAG_LIST];
    out.extend_from_slice(&(4u32).to_be_bytes());
    out.extend_from_slice(&value_codec::encode_value(&RowValue::String(table.to_string())));
    out.extend_from_slice(&value_codec::encode_value(&RowValue::String(field.to_string())));
    out.extend_from_slice(&value_codec::ordered_index_element(value));
    out.extend_from_slice(&value_codec::encode_value(&RowValue::String(record_id.to_string())));
    out
}

#[test]
fn dart_index_keys_match_the_rust_ordered_index_encoding() {
    let fixture: Value = serde_json
        ::from_str(&std::fs::read_to_string(fixture()).expect("fixture must exist"))
        .expect("fixture JSON must parse");
    let keys = fixture["indexKeys"].as_array().expect("indexKeys array");
    assert!(!keys.is_empty(), "fixture must carry index keys");
    for entry in keys {
        let label = as_str(&entry["label"], "index key label");
        let table = as_str(&entry["table"], "index key table");
        let field = as_str(&entry["field"], "index key field");
        let record_id = as_str(&entry["recordId"], "index key recordId");
        let expected = hex_decode(as_str(&entry["hex"], "index key hex"));
        let value = tagged_to_row(&entry["value"]);
        let actual = index_key_bytes(table, field, &value, record_id);
        assert_eq!(
            actual, expected,
            "index key {label} bytes must match the Dart encoder exactly \
             (a mismatch would make every cross-language index query miss)"
        );
    }
}
