#!/usr/bin/env dart
// Generates a deterministic public API snapshot for the gecko_db package.
//
// The snapshot is intentionally source-based and excludes implementation
// details. The checked-in public export list and declarations are included so
// a public surface change is visible in review and can be paired with an ADR.
// It does not replace analyzer-based API compatibility tooling.

import 'dart:io';

final _exportPattern = RegExp(
  r"^export '([^']+)'(?:\s+show\s+([\s\S]*?));$",
  multiLine: true,
);
final _declarationPattern = RegExp(
  r'^\s*(?:abstract\s+)?(?:class|enum|typedef|extension\s+type|mixin)\s+([A-Za-z_]\w*)',
  multiLine: true,
);

void main(List<String> args) {
  final output = args.isEmpty ? 'tool/api_snapshot.txt' : args.single;
  final entrypoint = File('packages/gecko_db/lib/gecko_db.dart');
  if (!entrypoint.existsSync()) {
    stderr.writeln('API SNAPSHOT FAILED: ${entrypoint.path} is missing.');
    exitCode = 1;
    return;
  }

  final source = entrypoint.readAsStringSync();
  final buffer = StringBuffer()
    ..writeln('# gecko_db public API snapshot')
    ..writeln('# Generated by tool/api_snapshot.dart')
    ..writeln('entrypoint: packages/gecko_db/lib/gecko_db.dart')
    ..writeln();

  final exports = _exportPattern.allMatches(source).map((match) {
    final path = match.group(1)!;
    final shown = match.group(2)?.replaceAll(RegExp(r'\s+'), ' ').trim() ?? '';
    return 'export: $path${shown.isEmpty ? '' : ' show: $shown'}';
  }).toList()..sort();
  for (final export in exports) {
    buffer.writeln(export);
  }

  buffer.writeln();
  buffer.writeln('entrypoint declarations:');
  final declarations =
      _declarationPattern
          .allMatches(source)
          .map((match) => match.group(1)!)
          .toSet()
          .toList()
        ..sort();
  for (final declaration in declarations) {
    buffer.writeln('declaration: $declaration');
  }

  final file = File(output);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(buffer.toString());
  stdout.write('Wrote ${file.path}\n');
}
